
import flight_plan
import flight_plan_generator
from . import PlanBase


class GeneratedCombinationsPlan(PlanBase):
    def get_items(self, **kwargs):
        plan = list()
        i = kwargs.pop('i')
        new_wp_locs = {
            6: flight_plan_generator.WaypointLocation(lat=43.467398, long=1.27016, alt=291),
            7: flight_plan_generator.WaypointLocation(lat=43.464681, long=1.265498, alt=278),
        }
        if new_wp_locs:
            plan += flight_plan_generator.move_waypoints(new_wp_locs)
        plan += [
            lambda: [  # 0
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(68),
            ],
            lambda: [  # 1
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(67),
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 2
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(65),
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(52),
            ],
            lambda: [  # 3
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(64),
            ],
            lambda: [  # 4
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(59),
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(68),
            ],
            lambda: [  # 5
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(69),
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(52),
            ],
            lambda: [  # 6
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 7
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(69),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 8
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 9
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(68),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(55),
            ],
            lambda: [  # 10
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(69),
            ],
            lambda: [  # 11
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(67),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 12
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(69),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(68),
            ],
            lambda: [  # 13
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(63),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(57),
            ],
            lambda: [  # 14
                flight_plan.JumpToBlock('Wait GPS'),
                flight_plan.WaitForState('Wait GPS'),
                flight_plan.WaitForSeconds(57),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(55),
            ],
            lambda: [  # 15
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(58),
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 16
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(50),
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(58),
            ],
            lambda: [  # 17
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(58),
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(62),
            ],
            lambda: [  # 18
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(53),
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(58),
            ],
            lambda: [  # 19
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(60),
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(64),
            ],
            lambda: [  # 20
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(67),
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 21
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(52),
            ],
            lambda: [  # 22
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(60),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(52),
            ],
            lambda: [  # 23
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(57),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(58),
            ],
            lambda: [  # 24
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(54),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 25
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(69),
            ],
            lambda: [  # 26
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(53),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(54),
            ],
            lambda: [  # 27
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 28
                flight_plan.JumpToBlock('Geo init'),
                flight_plan.WaitForState('Geo init'),
                flight_plan.WaitForSeconds(59),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 29
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(63),
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 30
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(53),
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 31
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(58),
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 32
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 33
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(55),
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(58),
            ],
            lambda: [  # 34
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(65),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(66),
            ],
            lambda: [  # 35
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(50),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(64),
            ],
            lambda: [  # 36
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(67),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(50),
            ],
            lambda: [  # 37
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(67),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(65),
            ],
            lambda: [  # 38
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(60),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(66),
            ],
            lambda: [  # 39
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 40
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(66),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 41
                flight_plan.JumpToBlock('Holding point'),
                flight_plan.WaitForState('Holding point'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 42
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(52),
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(66),
            ],
            lambda: [  # 43
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(57),
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(54),
            ],
            lambda: [  # 44
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(68),
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 45
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(54),
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 46
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(68),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(62),
            ],
            lambda: [  # 47
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 48
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(55),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 49
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(59),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(55),
            ],
            lambda: [  # 50
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(68),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(55),
            ],
            lambda: [  # 51
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(58),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 52
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(69),
            ],
            lambda: [  # 53
                flight_plan.JumpToBlock('Takeoff'),
                flight_plan.WaitForState('Takeoff'),
                flight_plan.WaitForSeconds(52),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 54
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(69),
            ],
            lambda: [  # 55
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(68),
            ],
            lambda: [  # 56
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(59),
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(65),
            ],
            lambda: [  # 57
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(60),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 58
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 59
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(54),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(64),
            ],
            lambda: [  # 60
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(67),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 61
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(57),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(59),
            ],
            lambda: [  # 62
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(64),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 63
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(53),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(64),
            ],
            lambda: [  # 64
                flight_plan.JumpToBlock('Standby'),
                flight_plan.WaitForState('Standby'),
                flight_plan.WaitForSeconds(50),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 65
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(65),
            ],
            lambda: [  # 66
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 67
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(60),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(69),
            ],
            lambda: [  # 68
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(65),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(69),
            ],
            lambda: [  # 69
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(52),
            ],
            lambda: [  # 70
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 71
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(69),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 72
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(60),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 73
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(62),
            ],
            lambda: [  # 74
                flight_plan.JumpToBlock('Figure 8 around wp 1'),
                flight_plan.WaitForState('Figure 8 around wp 1'),
                flight_plan.WaitForSeconds(50),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(57),
            ],
            lambda: [  # 75
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(54),
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(56),
            ],
            lambda: [  # 76
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(50),
            ],
            lambda: [  # 77
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 78
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(55),
            ],
            lambda: [  # 79
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(58),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 80
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(57),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 81
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(54),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 82
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(63),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 83
                flight_plan.JumpToBlock('Oval 1-2'),
                flight_plan.WaitForState('Oval 1-2'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(64),
            ],
            lambda: [  # 84
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 85
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(68),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 86
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(60),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(54),
            ],
            lambda: [  # 87
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(63),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(64),
            ],
            lambda: [  # 88
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(57),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(59),
            ],
            lambda: [  # 89
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 90
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(54),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 91
                flight_plan.JumpToBlock('MOB'),
                flight_plan.WaitForState('MOB'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(59),
            ],
            lambda: [  # 92
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(59),
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 93
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(68),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(56),
            ],
            lambda: [  # 94
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(52),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 95
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(62),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(52),
            ],
            lambda: [  # 96
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(59),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(62),
            ],
            lambda: [  # 97
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(59),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 98
                flight_plan.JumpToBlock('Survey S1-S2'),
                flight_plan.WaitForState('Survey S1-S2'),
                flight_plan.WaitForSeconds(52),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 99
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(54),
            ],
            lambda: [  # 100
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(66),
            ],
            lambda: [  # 101
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(55),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(69),
            ],
            lambda: [  # 102
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(55),
            ],
            lambda: [  # 103
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(64),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 104
                flight_plan.JumpToBlock('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForState('Path 1,2,S1,S2,STDBY'),
                flight_plan.WaitForSeconds(66),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(62),
            ],
            lambda: [  # 105
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(67),
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(60),
            ],
            lambda: [  # 106
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(69),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 107
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(61),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(53),
            ],
            lambda: [  # 108
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(53),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(55),
            ],
            lambda: [  # 109
                flight_plan.JumpToBlock('Land Right AF-TD'),
                flight_plan.WaitForState('Land Right AF-TD'),
                flight_plan.WaitForSeconds(69),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 110
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(58),
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(50),
            ],
            lambda: [  # 111
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(53),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(61),
            ],
            lambda: [  # 112
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(55),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 113
                flight_plan.JumpToBlock('Land Left AF-TD'),
                flight_plan.WaitForState('Land Left AF-TD'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(66),
            ],
            lambda: [  # 114
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(51),
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(58),
            ],
            lambda: [  # 115
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(63),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(67),
            ],
            lambda: [  # 116
                flight_plan.JumpToBlock('land'),
                flight_plan.WaitForState('land'),
                flight_plan.WaitForSeconds(50),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(63),
            ],
            lambda: [  # 117
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(56),
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 118
                flight_plan.JumpToBlock('final'),
                flight_plan.WaitForState('final'),
                flight_plan.WaitForSeconds(55),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(51),
            ],
            lambda: [  # 119
                flight_plan.JumpToBlock('flare'),
                flight_plan.WaitForState('flare'),
                flight_plan.WaitForSeconds(50),
                flight_plan.JumpToBlock('HOME'),
                flight_plan.WaitForState('HOME'),
                flight_plan.WaitForSeconds(59),
            ],
        ][int(i)]()
        plan.append(flight_plan.StopTest())
        return plan


Plan = GeneratedCombinationsPlan
__all__ = ['Plan']
